import { SiteConfig } from './types';

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  logoUrl: 'https://i.ibb.co/4n3RFDrL/bmg-logo-v2.png',
  backgroundColor: '#FFEEDF',
  pages: [
    {
      id: 1,
      title: 'BmGstudio',
      description: 'CRAFTING MOTION, INSPIRING STORIES.',
      mediaUrl: 'https://i.ibb.co/4n3RFDrL/bmg-logo-v2.png',
      mediaType: 'image',
      styles: {
        titleColor: '#000000',
        descriptionColor: '#FF007A',
        titleSize: 'text-8xl',
        descriptionSize: 'text-xl',
        fontFamily: 'font-sans',
      },
    },
    {
      id: 2,
      title: 'Our Vision',
      description: 'We believe in the power of visual storytelling to bridge the gap between imagination and reality.',
      mediaUrl: 'https://i.ibb.co/nNY49f6R/bmg-both-comp-002-00000.png',
      mediaType: 'image',
      styles: {
        titleColor: '#000000',
        descriptionColor: '#000000',
        titleSize: 'text-6xl',
        descriptionSize: 'text-lg',
        fontFamily: 'font-sans',
      },
    },
    {
      id: 3,
      title: 'Works',
      description: 'Explore our latest artwork and design explorations. (Click to view full gallery)',
      mediaUrl: 'https://i.ibb.co/ds5NrZWc/lying-white-1.png',
      mediaType: 'image',
      externalLink: 'https://drive.google.com/file/d/1th8WN1usKjF9_q6ERXg1Q7IUtXFvto1I/view?usp=sharing',
      styles: {
        titleColor: '#000000',
        descriptionColor: '#000000',
        titleSize: 'text-7xl',
        descriptionSize: 'text-lg',
        fontFamily: 'font-sans',
      },
    },
    {
      id: 4,
      title: 'Showreel 2024',
      description: 'Experience our creative process in motion.',
      mediaUrl: 'https://drive.google.com/file/d/1nkfbdiCXpsQFGienTfe44Kss-ufyED5q/view?usp=sharing',
      mediaType: 'video',
      externalLink: 'https://drive.google.com/file/d/1nkfbdiCXpsQFGienTfe44Kss-ufyED5q/view?usp=sharing',
      styles: {
        titleColor: '#000000',
        descriptionColor: '#000000',
        titleSize: 'text-6xl',
        descriptionSize: 'text-lg',
        fontFamily: 'font-sans',
      },
    },
    {
      id: 5,
      title: 'Connect',
      description: "Contact\n\nWe are ready to collaborate.\nLeave a trace in whatever way suits you.\n\ninstagram : @boy.meets.girl_\nemail : hello.bmgstudio.official@gmail.com",
      mediaUrl: 'https://i.ibb.co/KpDRZqh7/bmg-bridge-comp-mov-20231115-175726-909.jpg',
      mediaType: 'image',
      externalLink: 'mailto:hello.bmgstudio.official@gmail.com',
      styles: {
        titleColor: '#000000',
        descriptionColor: '#FF007A',
        titleSize: 'text-7xl',
        descriptionSize: 'text-xl',
        fontFamily: 'font-sans',
      },
    },
  ],
};
